# Generated by Django 5.1.3 on 2024-11-18 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0002_alter_mailing_options_alter_message_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailing",
            name="is_block",
            field=models.BooleanField(default=False, verbose_name="Блокировка"),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="status",
            field=models.CharField(
                choices=[
                    ("Создана", "Создана"),
                    ("Запущена", "Запущена"),
                    ("Завершена", "Завершена"),
                    ("Блокирована", "Блокирована"),
                ],
                default="Создана",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
    ]
